### PR TITLE
Fix #97 - Replace semicolons in UPSTREAM_DNS

### LINKED ISSUE #97: Support lancache-dns UPSTREAM_DNS syntax
The `lancache-dns` service supports multiple upstream DNS servers using the same environment variable as `generic`, but uses a slightly different syntax, which causes `nginx` to fail to start with a configuration file syntax error if both services are configured using the same value.

Replacing semicolons from `UPSTREAM_DNS` with spaces before populating the `nginx` config will resolve this.

### PR DESCRIPTION
**Pull request by GotenXiao**
This enables compatibility between the `lancache-dns` accepted format and the nginx accepted format used by `generic`.

### CODE REVIEW

**Comment by GotenXiao** [comment]
> Doesn't this need an export to elevate back to the controlling shell?

I'd assume that we'd want to retain the exact format of what's been passed in for the runtime environment - it's changed here to not break nginx's `resolver` directive.

When testing with a local build:
```bash
docker run --rm -it -e UPSTREAM_DNS="8.8.8.8; 8.8.4.4" generic:97-upstream-dns-compatibility
```
Results in:
```
...
# Including /etc/nginx/sites-available/generic.conf.d/10_generic.conf
resolver 8.8.8.8 8.8.4.4 ipv6=off;
...
Checking nginx config
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Config check successful
```

**Comment by GotenXiao** [comment]
Updated to resolve merge conflicts.

**Comment by VibroAxe** [comment]
@GotenXiao might need to look if the generate_hooks script in monolithic needs the same treatment

**Review by VibroAxe — COMMENTED** [review]
monolithic Needs checking with this change

**Pull request merged**
