### PR TITLE
Added low capacity hardware configuration

### PR DESCRIPTION
**Pull request by ScholliYT**
If verification is needed I can provide it.

### CODE REVIEW

**Comment by VibroAxe** [comment]
This seems very high on the core count, and low on both memory and disk io which is what actually drives the performance of a cache server. Claiming this would do 100MB/s "from hdd way slower" is a majorly false claim when with <4GB of memcache will serve almost no files from anything but the HDD.

**Comment by JasonRivers** [comment]
The Cache we ran at epic.LITE South was:
CPU: Quad-core AMD Phenom X4 II 945 (old!)
MEM: 16GB DDR3
Disk: 2x2TB RAID0 + 512MB SSD LVM Cache.

Without the LVM Cache the system would push around 300-400mb/s, with the SSD Cache we were pushing around 800-900mb/s

The read speed on a 5K disk is going to be around 30MB/s max, I agree with @VibroAxe that you will not hit 100MB/s using that setup.

**Comment by VibroAxe** [comment]
@ScholliYT if you can update the merge request with some of @JasonRivers comments. I think having a minimum spec is a good idea, it just needs to be accurate!

**Comment by ScholliYT** [comment]
Sorry I was a bit unclear. We hit 100MB/s when serving only from RAM. When serving from HDD @JasonRivers  is right. There is no way to get 100MB/s.

**Pull request merged**
