### PR TITLE
WIP: Added monolithic cache option

### PR DESCRIPTION
**Pull request by Crabbey**

### CODE REVIEW

**Comment by VibroAxe** [comment]
There is at least one bug with this so far, missing
`ln -s /etc/nginx/sites-available/generic.conf /etc/nginx/sites-enabled/generic.conf` in the Dockerfile

We are going to run this (Fixed in vibroaxe/generic:monolithic) at stratlan and report back. I would suggest not merging until then

Damn fine work though, initial results do look good

**Comment by Crabbey** [comment]
Addressed the missing symlink.

**Comment by VibroAxe** [comment]
On hold pending review for #70

**Comment by GotenXiao** [comment]
This looks awesome.

Suggestion - at the moment, these changes won't cold start without internet, as it'll try (and fail) to clone the git repo.

In the interests of being able to do that, I'd suggest that we add an `ARG` for the repo URL, and always clone the repo at build time. The use of `ARG` allows a user to replace the repo with a custom repo at build time, and then at first start we can compare the `ENV` value with the remote URL - if they differ, change the remote to match (e.g. `git remote set-url origin $CACHE_DOMAIN_REPO`, and the `git reset --hard origin/master` will change the contents over to match - but we can then make the script warn if the upstream repo URL hasn't changed, but fail noisily if it has.

**Comment by VibroAxe** [comment]
So we now have a fully functioning [steamcache/monolithic](https://github.com/steamcache/monolithic) which is built on this work and the supervisord rewrite. @Crabbey is awesome, thanks for the underlying work <3

I'm going to close the PR unless @Crabbey has any objections.

**Pull request closed without merging**
