### PR TITLE
Large rewrite and feature fixes

### PR DESCRIPTION
**Pull request by kixelated**
Hey guys, this is my steamcache fork rebased on generic this time. I'm sorry for the huge change but I wasn't originally planning on merging this upstream. 
 
I started running steamcache/generic at Twitch a few months now and have fixed most of the annoying bugs. Unfortunately each upstream has it's quirks, so this repo's "generic" approach to caching doesn't actually work. League never realizes there's an update, League/Origin run into e-tag errors, services with the same resource path collide, etc. It's possible to have separate IP addresses for each service but it's much easier to just inspect the Host header instead.

See https://github.com/steamcache/steamcache/pull/12 for some backstory when I tried to merge this code into steamcache (not generic).

I'd like to remove the hard-coded Google DNS and 900GB cache size limit. They aren't trivial changes so I will submit another code review if this gets merged.

### CODE REVIEW

**Comment by mintopia** [comment]
Hi, thanks for the PR.

Definitely agree with some of the changes in the PR, I have some concerns on the other ones.

I agree that the generic cache isn't working in all cases. I think it's worth providing some background as to why this image was created in the firstplace, and then we can move on to discussing the best way of fixing the issues.

The image was created as a generic image for caching, supporting range requests that would cache any hostname you throw at it. The reason for this is that I didn't want to have to rebuild the entire image everytime a new hostname was discovered or I wanted to cache a new service. Because of this, I don't want the generic image to have any hostnames defined in it.

Because of this, we can't nicely split it out into separate nginx server config blocks based on hostname, otherwise that's going to be annoying when someone adds yet another hostname to it, or we decide to host something new (like Steam Workshop). This means we can't have separate cache locations based on the server so there is a risk of cache collisions. This is why I always reccomend running a separate instance of the cache for every upstream service you're caching, with a different data directory mount.

The current problems we have had reported with specific services we're aiming to cache are:

 - Riot/Blizzard - Needs Etags ignoring
 - Riot - Needs slice disabling

So the question comes how to fix this. I see a few options:

1. We add support for environment variables, similar to steamcache-dns, eg. `UPSTREAM_SERVICE=blizzard` and have bootstrap.sh write out a new config based on that.
2. We create different tags of the image based on what we're supporting and have those tags support it. Similar to how the official docker images work for example with php or nginx and the different variants. `steamcache/generic:blizzard` or `steamcache/generic:riot`
3. We create a image based on `steamcache/generic` that makes the relevant changes. Then you just use `steamcache/riot` as your image.

Option 2 seems wrong and pointless as it's not generic. Option 3 would probably be best but has more overhead. Option 1 would make implementing Option 3 easy as it would just be an ENV directive in the Dockerfile to set the correct ENV for that variant.

What are your thoughts on it?

**Comment by kixelated** [comment]
Hey @mintopia,

I understand the desire to just rely on DNS for classification. It means you only have to update the DNS service to add new hostnames or new types of services. I've used multiplay/lancache in the past and it works the same way.

The biggest issue I'm trying to address is usability; I think it's too difficult for new users to set up steamcache. Large installations like yours should still be able to shard the services into different instances but we still need to make it easy for the small guys (like myself with just 10 PCs). I don't think we should ask new users to create 10 static IP addresses and run 10 instances of generic with different options.

1 instance of nginx is nice because it allows you to use the same proxy_cache_path for multiple services. I've set up my cache with a 1TB SSD and have a single proxy_cache_path with a (hard-coded for now) 900GB limit before the least used files are evicted. [multiple/lancache](https://github.com/multiplay/lancache/blob/master/sites/lancache.conf) also uses 1 nginx instance by binding each IP address in server blocks. You still to ask users to create and configure a unique IP address for each service.

Classifying requests based on the `Host` header (using `server_name`) means you can run a single instance of nginx on a single IP address. It makes it much simpler to set up a simple steamcache instance for yourself or a small network. The downside is that we need to maintain separate list of hostnames but that's really not bad. Professional setups can still run multiple instances with multiple IP addresses, just the `Host` header check will be redundant. And even if the DNS config is updated without updating the nginx config, requests will fall into the `generic` bucket.

Oh, and the DNS hostname management will be less of an issue as soon as [my branch is fully merged](https://github.com/steamcache/steamcache-dns/blob/dnsmasq/overlay/etc/dnsmasq.d/steamcache.conf.tmpl). Maybe this is enough to make multiple hostname classifications less annoying.

**Comment by kixelated** [comment]
To summarize the options:

**N ips, N nginx instances**
- hostnames only in DNS

**N ips, 1 nginx instance**
- hostnames only in DNS
- shared cache/logs

**1 ip, 1 nginx instance**
- doesn't require multiple IP addresses
- shared cache/logs

So it's a tradeoff between asking users to configure multiple IP addresses or make the project slightly easier to maintain. I know you'd like to have separate `generic` instances and differentiate them with environment variables but that's pretty convoluted. If you'd like separate IP addresses, I would recommend separate server blocks (how lancache does it) at the very least.

My biggest complaint with lancache was the difficulty to setup, which is why I love that steamcache uses Docker. I'd like to take it even further and [already have a branch that makes setup a one line command](https://github.com/kixelated/steamcache) (with docker and docker-compose installed). There's still a few improvements I need to make but it gives you an idea of the direction I'd like to head.

**Comment by GotenXiao** [comment]
I don't think requiring an IP per service is an arduous step for anyone looking to cache a number of services - it's more of a documentation problem than an operational problem. Example approaches include the following:
1. Add the following into `/etc/network/interfaces` (Ubuntu/Debian-based distros):
    ```
    iface eth0 inet dhcp
        post-up ip addr add 10.1.0.10/24 dev eth0
    ```
2. Add the following into `/etc/rc.local`:
    ```sh
    ip addr add 10.1.0.10/24 dev eth0
    ```
I would agree that we're currently lacking in that documentation, but given that we're talking about fairly cutting-edge tech with regards to containerisation anyway, I would hope that anyone starting out with it would have brushed up on some reasonably basic server administration.

Also, that complexity goes way down if your docker host has an entire subnet allocated to a docker network - in which case you configure your router to handle that, and you can allocate IPs directly to an entire container instance using the `--ip` flag either at the commandline via `docker run` or via a `docker-compose` stanza. For example:
```
$ docker network create -d bridge --gateway 192.168.9.1 --subnet 192.168.9.0/24 real-ips
32b6b11e7fb6aa8aa0efff8c43b02063dbc5b87d8449e7c709e897ece1dada35
$ docker network inspect real-ips
[
    {
        "Name": "real-ips",
        "Id": "32b6b11e7fb6aa8aa0efff8c43b02063dbc5b87d8449e7c709e897ece1dada35",
        "Created": "2017-04-17T21:40:10.178084803+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.9.0/24",
                    "Gateway": "192.168.9.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
$ docker run --net=real-ips --ip=192.168.9.10 -d --name steamcache steamcache/steamcache
```
At which point, the container instance is directly addressable at that IP, with no port punching or other configuration required. This does not require the docker proxy process, allows network admins to directly firewall, ratelimit, traffic shape, see complete breakdown of inbound caching traffic, etc. The downside is that this requires either a static route on all client machine, or the router to support static routing which is often not available on low-end consumer routers.

While the single-instance cache can indeed share a single cache folder (assuming the cache keys are not based on `$host`, which vastly reduces the effectiveness of the cache), there is another point to consider - these cache instances may not live on the same host node, and space consumption may need to be sharded for different services. Steam caches will always tend to use a lot more disk space than Blizzard, for example. In a larger containerised system, an administrator may have more than one active container host, and being able to migrate workloads is valuable. Tying every cache service into a single container reduces that manageability. I agree that disk space management remains an issue, especially with single-service containers sharing a single set of disks, and there is some ongoing investigation into managing that externally to nginx.

Given that we're talking about a container-based architecture, using layered images, there isn't a huge amount of additional overhead in issuing multiple container image names, one per service (as @mintopia suggests, either branch names a la `steamcache:blizzard` or as seperate image names entirely). This directly solves the problem of confusion of configuration, and means that no IP or hostname has to be in the configuration (unless required for that service). It also means that any updates to those services can be handled more cleanly, instead of requiring all services to be recycled.

The new user usecase can be directly addressed by using `docker-compose` and similar tools as you've mentioned, without sacrificing the high end flexibility required for larger scale setups. This also means that changing the configuration requires changing one file and re-running `docker-compose up -d`, whereas our current method requires a lot more effort for people not using Rancher or similar tools.

As an aside, thanks for your efforts on kicking our behinds into gear on this - we've been rather lax at keeping things moving.

**Comment by astrolox** [comment]
I must admit that I hadn't even considered IP addresses as a limited resource would be an issue for some people. I strongly feel that have separate containers and processes for different services being cached is preferable for ease of management and general separation principles.

If we can come to a solution that allows for **1 ip, N nginx instances** without a lot of maintenance burden then it sounds like something we should be supporting.

**Comment by kixelated** [comment]
Hey @GotenXiao, we should definitely document and enable users to run multiple steamcache instances. There are numerous situations where you want to segregate the services, such as host Steam downloads on a beefier host with a larger disk drive. All of your steps plus more could be documented for the people who run large-scale events.

But I'd like to make things more simple for the first-time user, or the small event organizer. I found this project semi-through the [Ars Technica](https://arstechnica.com/gaming/2017/01/building-a-local-steam-caching-server-to-ease-the-bandwidth-blues/) article which is aimed towards individuals. By the end of the article, you realize there's way too much manual work involved.

With 1-IP and 1-instance, you make it trivial to get lancache up and running for this target audience:

```
docker run -d -e LANCACHE_IP=10.0.0.1 steamcache/steamcache-dns:latest
docker run -d steamcache/generic:latest
```

The alternative you're proposing would look something like:

```
docker run -d -e BLIZZARDCACHE_IP=10.0.0.1 -e FRONTIERCACHE_IP=10.0.0.2 -e ORIGINCACHE_IP=10.0.0.3 -e RIOTCACHE_IP=10.0.0.4 -e STEAMCACHE_IP=10.0.0.5 -e UPLAYCACHE_IP=10.0.0.6 -e WINDOWSCACHE_IP=10.0.0.7 steamcache/steamcache-dns:latest
docker run -d --ip 10.0.0.1 steamcache/generic:blizzard
docker run -d --ip 10.0.0.2 steamcache/generic:frontier
docker run -d --ip 10.0.0.3 steamcache/generic:origin
docker run -d --ip 10.0.0.4 steamcache/generic:riot
docker run -d --ip 10.0.0.5 steamcache/generic:steam
docker run -d --ip 10.0.0.6 steamcache/generic:uplay
docker run -d --ip 10.0.0.7 steamcache/generic:windows
```

Sure, docker-compose will hide a lot of the ugly, but I don't understand why we should subject people to the extra complexity. Running and maintaining a separate container for each service is such an unnecessary burden.

And in case it wasn't clear, you can still run multiple instances of my container. The above configuration would work the exact same (minus the different tags) as the Host header will effectively be ignored. We get the benefit of making steamcache trivial to install and setup alongside the ability to really custom and start allocating IPs and hosts. Plus you're able to combine the caches for fringe services if you'd like.

@astrolox 1 IP, N nginx instances won't work. The instances won't be able to bind to port 80. You would need a load balancer like haproxy sitting in front that looks at the Host header... which is basically what I've done but with a single nginx instance.

**Comment by astrolox** [comment]
I/we see this as a generic reusable component which can be put to any use without modification. 

Imagine that you're part way through an event and you need to quickly add caching for something that you weren't aware of before. ... this should allow you do that by just starting a new container and adding some DNS entries.

At the moment we have problems relating to different services we want to cache behaving in different ways and needing slightly different options (such as slice yes/no). To keep with the philosophy I propose introducing configuration variables for each of these settings. So when starting a new container you get to choose which options are set or not.

I then propose extending that further with preset configurations which can be triggered, by either a variable and/or alternative docker tag. So that you don't have to know which options are required for something we support. However if that something changes and our preset is wrong, then you can still easily run the container with different options.

Ultimately this gives the image the ability to be applied to (hopefully / practically) anything without modification.

The view being presented by @kixelated focuses on usability from the point of view of adoption of this image and it's first time setup. I have to agree that the approach and philosophy outlined above has some downsides in that regards. The proposal being made solves those by switching to a *everything all ready done for you* type approach. This trades flexibility for a lower barrier to entry, and, to be fair, is probably the way to drive adoption.

I disagree with this proposal because I think the long term flexibility is more important than the short term getting up and running complexities. Essentially I'd say that providing *everything all ready done for you type approach* is the responsibility of a system which this image is just a component of, and is therefore not the responsibility of this image.

--

The main difference from a technical stand point is the inclusion of host names. Something which we currently maintain in the DNS image. I see maintaining this in two places as a problem - because the two locations will definitely become out of sync with each other. 

Obviously this can be solved by putting the list of hostnames somewhere else, say in it's own repository, and then having the two places that need it pull it in as a dependency. With some continuous integration we could ensure it's all always up to date. We could then accommodate all the different approaches being discussed here - through the use of configuration scripts.

However at that point I'd ask ... do we want that level of complexity in the images just to reduce the barrier to entry?

**Review by astrolox — COMMENTED** [review]
I'm guessing this wouldn't build on windows. Not sure.
https://github.com/steamcache/generic/pull/15/commits/ed3b931fe944e4787038437c8824e1983e970c71

**Comment by kixelated** [comment]
I'm fine with using a different repository if you would like to preserve the generic cache. I originally made the pull request for steamcache but was redirected here. 

The idea of forking generic for each, almost identical service, seems like a ton of overhead to retain the spirit of the repository. Users will have to provision ten IP addresses, (optionally) modify and build ten branches/images, run ten containers with different arguments, and watch the cache/log for ten instances. Or you can eat the cost of an extra list of hostnames and reduce everything down to one copy.

Also, you can still run my image as a generic cache because of the default server. Point any traffic at the instance and it will be cached, with slightly different logic if it matches the hostname list. It's a superset of the current generic image in that regard.

**Comment by ekhoury2000** [comment]
Hi @kixelated @mintopia @astrolox @GotenXiao 

First let me say that i really appreciate all the efforts here and i would like to assist you in any way i can.

First let me introduce myself, My name is Elie and, in addition to my passion in gaming and technology, i  am a Senior System Administrator in a real large bank.

My experience is mainly not development but i know algorithms and few languages too.

I have tested steamcache image and generic image, for steamcache, i think you all agree it is for now the best was to cache steam downloads and i cannot but agree more since i have implemented it and its working more than fine.

for the generic image, i implemented it on another server not because of the port 80, Ip address restrictions since that is solvable by adding several interfaces on the server, but i noticed that performance wise, its even better since i am using a virtual machine.

i can confirm that for riot, its working for me with no issue since i implemented sni, but for blizzard, even when i added proxy_hide_header ETag; blizzard couldn't update and games in battlenet were stuck on "fetching cdn configuration". I think if this issue is being focused, you can get a fully working generic image.

Please let me know if i can be of any help based on my experience and thanks again for you efforts,

**Comment by astrolox** [comment]
Hi - I just wish to confirm that once I have some free time I plan to come and give this the attention it deserves.

**Comment by mohsinskynet** [comment]
where to find nginx file to change the CACHE_MEM_SIZE, CACHE_DISK_SIZE, CACHE_MAX_AGE
and how to run Game Content Cache Hostnames please post a guide or tell here ty

**Comment by VibroAxe** [comment]
@kixelated just catching up with this PR, we went down a different route in the end, but I think you might be interested in [monolithic](/steamcache/monlithic) which has some similarities to this and is based on the updated version of generic

**Pull request closed without merging**
