### PR TITLE
Upstream DNS editable 

### PR DESCRIPTION
**Pull request by b-reich**
Make the Upstream DNS easy editable

### CODE REVIEW

**Comment by mintopia** [comment]
Just fixed a merge issue where the heartbeat functionality has been added.

**Comment by VibroAxe** [comment]
Changes look good to me

**Comment by rotanid** [comment]
the sniproxy in a docker-compose setup doesn't honor this env variable yet

**Comment by b-reich** [comment]
i write a small patch for it

**Comment by b-reich** [comment]
@rotanid checkout my repo please. I will maintaine a fork of the whole project.

**Pull request merged**
