### PR TITLE
Lancache version 2 Supervisord rewrite

### PR DESCRIPTION
**Pull request by VibroAxe**
This is a total refactor of generic to run through supervisord instead of our single bootstrap.sh script

## Brief features and changes overview
* Nginx now started by supervisord in base image (/etc/supervisord/conf.d/nginx.conf runs /opt/startnginx.sh)
* Heartbeat now started by supervisord (overlay/etc/supervisor/conf.d/heartbeat.conf)
* bootstrap.sh now run through supervisord hooks (overlay/hooks)
* nginx and generic config is now sharded to allow easier overriding of individual sections. (See later)

## Advantages ## 
* SupervisorD handles process management
* Layered config files, significantly improves ability to layer custom images on top whilst retaining updates from the base image
* Steamcache/steamcache and Steamcache/monolithic could both layer from this file to minimise differences between the images and benefit simply from PR's without having to change all the images we maintain

## Compatibility ##
Docker image is fully backwards compatible with existing docker image command line, env vars and cache data directories

## Testing ## 
* This image has been run throughout stratlan (with a further monolithic cache overlay which can currently be found at vibroaxe/monolithic)
* No issues found

## New Structure Explanation ##
nginx and generic config is now sharded to allow easier overriding of individual sections.
* overlay/etc/nginx/nginx.conf (primary config)
* overlay/etc/nginx/conf.d/* (top level config includes)
  * overlay/etc/nginx/conf.d/10_log_format.conf (The defined log format for steamcache)
  * overlay/etc/nginx/conf.d/20_proxy_cache_path.conf (The defined proxy cache stucture)
* overlay/etc/nginx/sites-available/* (All sites files)
  * overlay/etc/nginx/sites-available/10_generic.conf (Base level steamcache/generic file includes)
    * overlay/etc/nginx/sites-available/generic.conf.d/* (All generic conf files
      * overlay/etc/nginx/sites-available/generic.conf.d/10_generic.conf (Defines location blocks for / LoL and heartbeat)
      * overlay/etc/nginx/sites-available/generic.conf.d/root/* (Include files for / location block)
        * overlay/etc/nginx/sites-available/generic.conf.d/root/10_loop_detection.conf (loop detection)
        * overlay/etc/nginx/sites-available/generic.conf.d/root/20_cache.conf (main cache config declarations)
        * overlay/etc/nginx/sites-available/generic.conf.d/root/30_cache_key.conf (cache key, split for ease of overriding in monolithic)
        * overlay/etc/nginx/sites-available/generic.conf.d/root/40_etags.conf (etag handing)
        * overlay/etc/nginx/sites-available/generic.conf.d/root/90_upstream.conf (upstream proxy headers)
        * overlay/etc/nginx/sites-available/generic.conf.d/root/99_debug_header.conf (debug headers to aid clients)

### CODE REVIEW

**Comment by VibroAxe** [comment]
just finishing up a few reworks which occurred to me whilst rewriting the PR

**Comment by VibroAxe** [comment]
Added unit tests using https://goss.rocks/, WIP is now complete and ready for review and discussion

**Comment by mintopia** [comment]
As discussed at StratLAN, I'm 100% happy for this to be merged.  It's proven under load and has clear advantages over the previous version.

**Review by mintopia — APPROVED** [review]
Looks good to me.

**Review by JasonRivers — APPROVED** [review]
Chat with @VibroAxe. We should tag the current image as V1 just in case before merging.

**Comment by GotenXiao** [comment]
LGTM, with comments:
- By using a custom base image, we need to take responsibility for issuing new versions of that base image for security patches, etc, as its base image receives updates. Previously this could be done by an individual fairly trivially, by rebuilding our image with `--pull`, and they would receive security updates published via the `nginx` image, where this automation has already been done.
- We should aim to have a replacement for the cache test page that is used in the new version that can be run both without internet access (e.g. self-contained, self-hosted dynamically generated page), and without incurring load on a third party, especially in the event of a failure to cache on our part.

**Comment by GotenXiao** [comment]
After conversations:
- Creating our own base image from `ubuntu:bionic` instead of using `1and1internet/ubuntu-18-nginx:latest` seems to make more sense. The upstream has a lot of use-case specific modifications that don't necessarily line up with our own.
- Custom base image security concerns can be alleviated by using Docker Hub's automated build repository linking to declare our build dependencies.
- `cache_test.sh` only runs during unit tests at present, this doesn't cause undue concern to external parties.

**Comment by VibroAxe** [comment]
Created new base images: 
https://github.com/steamcache/ubuntu
and
https://github.com/steamcache/ubuntu-nginx

These are being automatically built at https://hub.docker.com/steamcache/ubuntu and https://hub.docker.com/steamcache/ubuntu-nginx and have been setup to autobuild on base repo build.

Last ubuntu image was pushed 15 days ago, i'm currently struggling to find "when" the base image gets updated. However we can run a cron/webhook if we feel that the builds aren't running regularly enough to pickup the relevant security patches etc. One to be monitored I feel.

Currently all 3 images (ubuntu:latest, ubuntu-nginx:latest and generic:supervisord) are successfully running their unit tests

If @GotenXiao and @JasonRivers would be so kind as to take a quick look at the base images and pick me up on anything I've done wrong that would be great. If nothing else jumps out then we are clear to build

**Comment by VibroAxe** [comment]
Woo, CI on generic!

**Comment by VibroAxe** [comment]
Approval received. Pulling the trigger. This will not currently deploy through circleci, but through docker hubs automated build process instead.

Circle CI deployment coming later

**Pull request merged**
